FROM public.ecr.aws/lambda/python:3.12

# Install system dependencies needed for LibreOffice
RUN dnf -y install \
    nss glibc fontconfig cups-libs \
    libX11 libXext libX11-xcb libxcb \
    mesa-libGL libXrender libSM libICE libXinerama \
    cairo cairo-devel libxslt \
    libstdc++ libgcc freetype \
    liberation-fonts xz-libs bzip2-libs \
    wget tar java-17-amazon-corretto-devel findutils \
    glibc-langpack-en glibc-locale-source \
    strace gdb \
    && dnf clean all && rm -rf /var/cache/dnf

# Generate en_US.UTF-8 locale
RUN localedef -i en_US -f UTF-8 en_US.UTF-8

# Ensure locale is set
RUN echo "LANG=en_US.UTF-8" >> /etc/environment && \
    echo "LANGUAGE=en_US:en" >> /etc/environment && \
    echo "LC_ALL=en_US.UTF-8" >> /etc/environment

# Download and extract LibreOffice
RUN wget https://download.documentfoundation.org/libreoffice/stable/25.2.2/rpm/x86_64/LibreOffice_25.2.2_Linux_x86-64_rpm.tar.gz && \
    mkdir -p /tmp/rpms && \
    tar -xzf LibreOffice_25.2.2_Linux_x86-64_rpm.tar.gz -C /tmp/rpms && \
    rm LibreOffice_25.2.2_Linux_x86-64_rpm.tar.gz

# Install LibreOffice headless essentials
RUN rpm -ivh \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libreoffice25.2-ure-25.2.2.2-2.x86_64.rpm \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libobasis25.2-core-25.2.2.2-2.x86_64.rpm \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libobasis25.2-images-25.2.2.2-2.x86_64.rpm \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libreoffice25.2-25.2.2.2-2.x86_64.rpm \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libobasis25.2-writer-25.2.2.2-2.x86_64.rpm \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libobasis25.2-ooofonts-25.2.2.2-2.x86_64.rpm \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libobasis25.2-en-US-25.2.2.2-2.x86_64.rpm \
    /tmp/rpms/LibreOffice_25.2.2.2_Linux_x86-64_rpm/RPMS/libreoffice25.2-en-US-25.2.2.2-2.x86_64.rpm \
    && rm -rf /tmp/rpms


RUN ls -lart /usr/lib64/ 

# Initialize font cache and copy fonts
RUN fc-cache -f && \
    mkdir -p /usr/share/libreoffice && \
    cp -r /opt/libreoffice25.2/share/* /usr/share/libreoffice/ && \
    chmod -R 755 /usr/share/libreoffice