AWSTemplateFormatVersion: '2010-09-09'
Description: 'Storage infrastructure for Pharma RAG system'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, dev-1, dev-2, staging, prod]
    Description: Environment name

Resources:
  # S3 Bucket - Note: If bucket already exists externally, this will fail
  # Solution: Ensure bucket is created manually first or let CloudFormation handle it
  DocumentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # Remove BucketName to make it idempotent - CloudFormation will generate unique name
      # or use the existing bucket if recreating
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - ETag
              - x-amz-version-id
            MaxAge: 3000
      Tags:
        - Key: Name
          Value: !Sub 'pharma-documents-${Environment}'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DocumentBucketName:
    Description: S3 Bucket for document storage
    Value: !Ref DocumentBucket
    Export:
      Name: !Sub '${AWS::StackName}-DocumentBucketName'

  DocumentBucketArn:
    Description: S3 Bucket ARN for document storage
    Value: !GetAtt DocumentBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DocumentBucketArn'
