# Build Docling with Tesseract OCR for document processing
# This workflow builds and pushes Docker images to GitHub Container Registry
name: Build Docling with Tesseract

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCLING_IMAGE: ${{ github.repository_owner }}/docling
  TESSERACT_IMAGE: ${{ github.repository_owner }}/tesseract-lambda

jobs:
  # Main job that handles cleanup, building, and pushing Docker images
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cleanup workspace before build
      run: |
        echo "🧹 Cleaning up workspace before Docling build..."
        
        # Clean up temporary files and caches
        sudo rm -rf /tmp/*
        sudo rm -rf /var/tmp/*
        sudo rm -rf /var/cache/apt/archives/*
        sudo rm -rf /var/log/*
        sudo find /var/log -type f -name "*.log" -delete
        
        # Clean up Docker system
        docker system prune -af --volumes
        
        # Clean up any existing build artifacts
        rm -rf .dockerignore
        rm -rf *.log
        rm -rf build/
        rm -rf dist/
        rm -rf node_modules/ 2>/dev/null || true
        rm -rf .pytest_cache/ 2>/dev/null || true
        rm -rf __pycache__/ 2>/dev/null || true
        rm -rf .coverage 2>/dev/null || true
        rm -rf .mypy_cache/ 2>/dev/null || true
        
        # Clean up Python cache files
        find . -name "*.pyc" -delete
        find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
        find . -name "*.pyo" -delete
        find . -name "*.pyd" -delete
        find . -name "*.egg-info" -type d -exec rm -rf {} + 2>/dev/null || true
        find . -name "*.dist-info" -type d -exec rm -rf {} + 2>/dev/null || true
        
        # Clean up any test files
        find . -name "test_*" -type f -delete 2>/dev/null || true
        find . -name "*_test.py" -type f -delete 2>/dev/null || true
        find . -name "tests" -type d -exec rm -rf {} + 2>/dev/null || true
        
        # Show disk usage before build
        echo "📊 Disk usage before build:"
        df -h
        du -sh . || true
        
        echo "✅ Workspace cleanup completed!"
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push Tesseract image
      run: |
        echo "🔨 Building Tesseract image..."
        docker build -f Dockerfile.tesseract -t ${{ env.REGISTRY }}/${{ env.TESSERACT_IMAGE }}:latest .
        
        echo "📤 Pushing Tesseract image to GitHub Container Registry..."
        docker push ${{ env.REGISTRY }}/${{ env.TESSERACT_IMAGE }}:latest
        
    - name: Build and push Docling image
      run: |
        echo "🔨 Building Docling image with cleanup optimizations..."
        docker build -f Dockerfile.docling -t ${{ env.REGISTRY }}/${{ env.DOCLING_IMAGE }}:latest .
        
        echo "📤 Pushing Docling image to GitHub Container Registry..."
        docker push ${{ env.REGISTRY }}/${{ env.DOCLING_IMAGE }}:latest
        
    - name: Cleanup after build
      if: always()
      run: |
        echo "🧹 Final cleanup after build..."
        
        # Remove Docker images to free space
        docker rmi $(docker images -q) 2>/dev/null || true
        docker system prune -af --volumes
        
        # Show final disk usage
        echo "📊 Final disk usage:"
        df -h
        
        echo "✅ Build cleanup completed!"
        
    - name: Upload build logs
      if: failure()
      run: |
        echo "📋 Collecting build logs for debugging..."
        mkdir -p build-logs
        find . -name "*.log" -exec cp {} build-logs/ \; 2>/dev/null || true
        docker logs $(docker ps -aq) > build-logs/docker-logs.txt 2>/dev/null || true
        echo "📊 Build artifacts collected:"
        ls -la build-logs/ || echo "No logs found"
        
    - name: Upload artifacts
      if: failure() && (contains(github.event.head_commit.message, 'debug') || contains(github.event.head_commit.message, 'logs'))
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build-logs/
        if-no-files-found: ignore
        retention-days: 7
